//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbhotel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BBHotelEntities : DbContext
    {
        private static BBHotelEntities context;
        public static BBHotelEntities getContext()
        {
            if (context == null)
                context = new BBHotelEntities();
            return context;
        }
        public BBHotelEntities()
            : base("name=BBHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apartment> apartment { get; set; }
        public virtual DbSet<apartments> apartments { get; set; }
        public virtual DbSet<booking> booking { get; set; }
        public virtual DbSet<Guest> Guest { get; set; }
        public virtual DbSet<HotelImage> HotelImage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
