//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbhotel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id_booking { get; set; }
        public int id_apartment { get; set; }
        public int id_guest { get; set; }
        public string rent_type { get; set; }
        public System.DateTime check_in { get; set; }
        public System.DateTime check_out { get; set; }
        public string cost { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual apartment apartment { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
